set(ASAN OFF)
set(UBSAN OFF)
set(NONET ON)
set(PACKET_ENCRYPTION OFF)
set(DEFAULT_PER_PIXEL_LIGHTING false)
set(DISABLE_DEMOMODE ON)
set(DISABLE_LTO ON)
set(DEVILUTIONX_SYSTEM_SDL_IMAGE OFF)
set(BUILD_TESTING OFF)
set(PREFILL_PLAYER_NAME ON)
set(NOEXIT ON)

set(BUILD_ASSETS_MPQ OFF)
set(UNPACKED_MPQS ON)

# Use lower resampling quality for FPS.
set(DEFAULT_AUDIO_RESAMPLING_QUALITY 2)
set(DEVILUTIONX_DISPLAY_TEXTURE_FORMAT "SDL_PIXELFORMAT_ABGR1555")
set(DEVILUTIONX_GAMEPAD_TYPE PlayStation)